---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barlom-app
  labels:
    app: barlom
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: barlom
  replicas: 2
  template:
    metadata:
      labels:
        app: barlom
    spec:
      containers:
        - name: bar-app
          image: localhost:32000/barlom:latest
          ports:
          - containerPort: 8080
            name: http-api
          - containerPort: 8081
            name: http-health
          env:
            - name: ENV_SAMPLE
              value: Example
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: barlom-ingress
spec:
  rules:
    - http:
        paths:
          - path: /barlom
            backend:
              serviceName: barlom-app
              servicePort: 8080
          - path: /barlom-health
            backend:
              serviceName: barlom-app
              servicePort: 8081
